branches:
  only:
    - master
language: objective-c
osx_image: xcode7.3
cache:
  - cocoapods
xcode_project: m8s.xcodeproj
xcode_scheme: m8s
before_install:
  - gem install cocoapods -v '1.0.0'
install:
- |
  bundle install
  bundle exec pod repo update
  bundle exec pod install
